### ISSUE TITLE
The nodes of a way aren't imported in SQLite

### ISSUE THREAD

**Issue by maxlorenz** [Greennav/service-database#7]
In the [sqlite](https://github.com/Greennav/service-database/blob/master/database/sqlite/sqlite.go) implementation, the `WriteWayNodes`-function doesn't get any nodes from the way. The query does work (tested in sqlite3 directly) but the nodes seem to be empty. For implementation please see [here](https://github.com/omniscale/imposm3/blob/master/element/element.go)

**Comment by JRonak** [comment]
Tried to understand imposm3's decoding, looks like the nodes of the way aren't populated at all. Is there a way we can do it using the references?
https://github.com/omniscale/imposm3/blob/master/parser/pbf/pbf.go

**Comment by jronak** [comment]
The number of way nodes is equal to the length of the refs and the node Id is the value of refs. These ref values are supposed to be the node Id's. But node Id value extracted from the refs are not present as a node in imposm3.

I used another package for osmPbf: https://github.com/thomersch/gosmparse/blob/master/elements.go. After testing, I found that the number of nodes produced by it was very large compared to imposm3 and it had all the nodes referred by the Refs. 

Need some heads up here, thank you

**Comment by jronak** [comment]
Bingo found the solution. 

We were parsing only the Nodes with tags in the Pbf.Parser method. We need to consider the Coords also as it parses all the nodes but which do not have any tags. These Way.Refs contain ids of the Coords and hence can be used to populate.

Will be sending pull request soon
